//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int id { get; set; }
        public string cliente { get; set; }
        public string nit { get; set; }
        public Nullable<int> producto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual producto producto1 { get; set; }
    }
}
